package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	yt_transcript_api "github.com/dogslee/youtube_transcript_api"
)

func main() {
	var (
		listTranscripts        = flag.Bool("list-transcripts", false, "List the languages in which the given videos are available in")
		languages              = flag.String("languages", "en", "A list of language codes in a descending priority (space-separated)")
		excludeGenerated       = flag.Bool("exclude-generated", false, "Exclude transcripts which have been generated by YouTube")
		excludeManuallyCreated = flag.Bool("exclude-manually-created", false, "Exclude transcripts which have been manually created")
		format                 = flag.String("format", "pretty", "Output format: json, pretty, text, webvtt, srt")
		translate              = flag.String("translate", "", "The language code for the language you want this transcript to be translated to")
		webshareProxyUsername  = flag.String("webshare-proxy-username", "", "Webshare Proxy Username")
		webshareProxyPassword  = flag.String("webshare-proxy-password", "", "Webshare Proxy Password")
		httpProxy              = flag.String("http-proxy", "", "HTTP proxy URL")
		httpsProxy             = flag.String("https-proxy", "", "HTTPS proxy URL")
		version                = flag.Bool("version", false, "Show version information")
	)

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [options] <video_id> [video_id ...]\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "This is a Go API which allows you to get the transcripts/subtitles for a given YouTube video.\n")
		fmt.Fprintf(os.Stderr, "It also works for automatically generated subtitles and it does not require a headless browser.\n\n")
		fmt.Fprintf(os.Stderr, "Options:\n")
		flag.PrintDefaults()
	}

	flag.Parse()

	if *version {
		fmt.Println("youtube-transcript-api (Go version), version", yt_transcript_api.Version)
		os.Exit(0)
	}

	if flag.NArg() == 0 {
		flag.Usage()
		os.Exit(1)
	}

	videoIDs := flag.Args()

	// 解析语言列表
	languageList := []string{"en"}
	if *languages != "" {
		languageList = strings.Fields(*languages)
	}

	config := yt_transcript_api.CLIConfig{
		VideoIDs:               videoIDs,
		ListTranscripts:        *listTranscripts,
		Languages:              languageList,
		ExcludeGenerated:       *excludeGenerated,
		ExcludeManuallyCreated: *excludeManuallyCreated,
		Format:                 *format,
		Translate:              *translate,
		WebshareProxyUsername:  *webshareProxyUsername,
		WebshareProxyPassword:  *webshareProxyPassword,
		HTTPProxy:              *httpProxy,
		HTTPSProxy:             *httpsProxy,
	}

	cli := yt_transcript_api.NewYouTubeTranscriptCLI(config)
	output, err := cli.Run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if output != "" {
		fmt.Println(output)
	}
}
